### PR TITLE
searchTerm rencoding

### PR DESCRIPTION
**Pull request by juanma-cvega**
Rencode searchTerm parameter as the Emby server is expecting + as %2B for AND queries. This is added so other addons are able to call the search function with %2B without it being decoded to + which doesn't work with the Emby API.

### CODE REVIEW

**Comment by juanma-cvega** [comment]
Hi @faush01 . I took the liberty of creating this pull request hoping you can merge it if you don't see any problems with it. While using TheMovieDB Helper I realised I couldn't pass "%2B" when using the search function with the parameter "searchTerm" as it was decoded to +. I tested locally and it seems to work both using your addon and TheMovieDB Helper. Feel free to comment, close or merge the pull request as you see fit.

**Comment by faush01** [comment]
can you give me an example of a few full add-on query call strings that are having the issue?
i am looks for what method the other add-ons are using to call the search.

**Comment by juanma-cvega** [comment]
Here is the example I've been working with. The following is a log from calling Embycon from TheMovieDb Helper

Script argument data: ['plugin://plugin.video.embycon/', '18', '?content_type=video&mode=GET_CONTENT&media_type=episodes&url=%7Bserver%7D%2Femby%2FUsers%2F%7Buserid%7D%2FItems**%3FsearchTerm%3DAll%2BMight**%26IncludeItemTypes%3Depisode%26IncludeMedia%3Dtrue%26filters%3DIsNotFolder%26fields%3DMediaStreams%26Recursive%3Dtrue%26ImageTypeLimit%3D1%26Limit%3D16', 'resume:false']

And this is the end call the addon makes to the Emby server:
https://host:443/emby/Users/{userId}/Items?**searchTerm=All+Might**&IncludeItemTypes=episode&IncludeMedia=true&filters=IsNotFolder&fields=MediaStreams&Recursive=true&ImageTypeLimit=1&Limit=16

The %2B is decoded into + which the Emby server doesn't recognize so the result includes every episode that contains either "All" or "might" instead of those containing "All might"

**Comment by faush01** [comment]
I am not sure this is an EmbyCon issue.

When creating the plugin call you need to double encode the search string like this

```
import urllib

search_txt = "All+Might"
search_txt = urllib.quote(search_txt)
print search_txt + "\r\n"

url = "{server}/emby/Users/{userid}/Items?searchTerm=" + search_txt + "&IncludeItemTypes=episode&IncludeMedia=true&filters=IsNotFolder&fields=MediaStreams&Recursive=true&ImageTypeLimit=1&Limit=16"

final_url = urllib.quote(url)
print final_url + "\r\n"

unquoted = urllib.unquote(final_url)
print unquoted + "\r\n"
```

**Comment by faush01** [comment]
the above produces

`%7Bserver%7D/emby/Users/%7Buserid%7D/Items%3FsearchTerm%3DAll%252BMight%26IncludeItemTypes%3Depisode%26IncludeMedia%3Dtrue%26filters%3DIsNotFolder%26fields%3DMediaStreams%26Recursive%3Dtrue%26ImageTypeLimit%3D1%26Limit%3D16`

That can be used int he url= of the GET_CONTENT call

**Comment by juanma-cvega** [comment]
I think I understand when you say it's not an EmbyCon issue as, for what I understand, the addon is expecting an encoded url to decode it a make the call but then the Emby server is also expecting the searchTerm encoded as well. The problem I have is that the TheMovieDB helper addon works by creating players, not coding a solution. Currently, you can use encoded predefined values inside the player but these are provided by the addon, you don't have the option to invoke a function as many times as you want per parameter. So in the end, if this is not something you want to merge to your repository, I can close it and just keep the fork for my own use.
By the way, I made another modification to show extra information per line when a single entry contains different video tracks. It looks like [this](https://pasteboard.co/J3KgEw6.png):

If it's something you find useful, I can create another pull request for it.

**Comment by faush01** [comment]
The problem is if a client is doing the correct thing and correctly encoding the search string this change will break that.
I have come across the player config thing before was not able to find a good solution with the current methods in use.
The better way would be to add a custom mode=SEARCH or enhance the current SEARCH mode to take in a search string on the add-on line that only needs to be encoded the once.
This might be a better more robust solution than trying to use the GET_CONTENT mode

**Comment by faush01** [comment]
Yeah send through the PR for the extra info, I assume it is just adding multi line info using the Label2 to the ListItems used in the selection dialog?

**Comment by faush01** [comment]
You might be able to use the NEW_SEARCH type:

?mode=NEW_SEARCH&item_type=movie&query=All%2BMight

**Comment by juanma-cvega** [comment]
The author of TheMovieDB Helper agreed to provide a double encoded version of the title so now there is no need for this change anymore. Interestingly enough, there is still an edge case that I think falls on the EmbyCon side. I tested it with an episode called `Boy Meets...`. After EmbyCon decodes the value, the result contains the ... as a single character, which makes it fail the search. Do you think there is something you can you from your side?

This is the string received by the addon from TheMovieDB Helper:

2020-04-15 20:52:55.809 T:123145512206336  NOTICE: EmbyCon.resources.lib.functions|DEBUG|Script argument data: ['plugin://plugin.video.embycon/', '14', '?content_type=video&mode=GET_CONTENT&media_type=episodes&url=%7Bserver%7D%2Femby%2FUsers%2F%7Buserid%7D%2FItems%3FYears%3D+%26IncludeItemTypes%3Depisode%26IncludeMedia%3Dtrue%26filters%3DIsNotFolder%26fields%3DMediaStreams%26Recursive%3Dtrue%26ImageTypeLimit%3D1%26MinPremiereDate%3D2019-10-26%26**searchTerm%3DBoy%252BMeets\xe2\x80\xa6**%26MaxPremiereDate%3D2019-10-26%26Limit%3D16', 'resume:false']

And this is the http call to the Emby server:

2020-04-15 20:52:55.850 T:123145512206336  NOTICE: EmbyCon.resources.lib.downloadutils|DEBUG|After: https://host:443/emby/Users/userid/Items?Years=+&IncludeItemTypes=episode&IncludeMedia=true&filters=IsNotFolder&fields=MediaStreams&Recursive=true&ImageTypeLimit=1&MinPremiereDate=2019-10-26&**searchTerm=Boy%2BMeets…**&MaxPremiereDate=2019-10-26&Limit=16

**Comment by juanma-cvega** [comment]
> You might be able to use the NEW_SEARCH type:
?mode=NEW_SEARCH&item_type=movie&query=All%2BMight

What's the difference between this one and the other?
I actually wanted to ask you something about a use case I don't know this new functionality could help with. The episodes in the Emby server are scraped using TVDB but TheMovieDB Helper uses TMDB. Normally I can use the episode title in a search but there are cases, specially with anime, where the name differs. I've seen that I can bypass the limitation by using the premiered date instead of the name of the episode but for that I need the ParentId from Emby for the TV show. Normally this wouldn't be a problem as for TV shows Emby has the TMDB id of the show but that would mean making two calls to Emby (first one to find the ParentId and second to make a search with premiered date and ParentId) which I can't do through TheMovieDB Helper. Is there any way I can pass the TV show TMDB ID plus the search string so EmbyCon takes care of transforming the TMDB ID into the ParentId?

**Comment by faush01** [comment]
> 
> 
> The author of TheMovieDB Helper agreed to provide a double encoded version of the title so now there is no need for this change anymore. Interestingly enough, there is still an edge case that I think falls on the EmbyCon side. I tested it with an episode called `Boy Meets...`. After EmbyCon decodes the value, the result contains the ... as a single character, which makes it fail the search. Do you think there is something you can you from your side?
> 
> This is the string received by the addon from TheMovieDB Helper:
> 
> 2020-04-15 20:52:55.809 T:123145512206336 NOTICE: EmbyCon.resources.lib.functions|DEBUG|Script argument data: ['plugin://plugin.video.embycon/', '14', '?content_type=video&mode=GET_CONTENT&media_type=episodes&url=%7Bserver%7D%2Femby%2FUsers%2F%7Buserid%7D%2FItems%3FYears%3D+%26IncludeItemTypes%3Depisode%26IncludeMedia%3Dtrue%26filters%3DIsNotFolder%26fields%3DMediaStreams%26Recursive%3Dtrue%26ImageTypeLimit%3D1%26MinPremiereDate%3D2019-10-26%26**searchTerm%3DBoy%252BMeets\xe2\x80\xa6**%26MaxPremiereDate%3D2019-10-26%26Limit%3D16', 'resume:false']
> 
> And this is the http call to the Emby server:
> 
> 2020-04-15 20:52:55.850 T:123145512206336 NOTICE: EmbyCon.resources.lib.downloadutils|DEBUG|After: [https://host:443/emby/Users/userid/Items?Years=+&IncludeItemTypes=episode&IncludeMedia=true&filters=IsNotFolder&fields=MediaStreams&Recursive=true&ImageTypeLimit=1&MinPremiereDate=2019-10-26&**searchTerm=Boy%2BMeets…**&MaxPremiereDate=2019-10-26&Limit=16](https://host:443/emby/Users/userid/Items?Years=+&IncludeItemTypes=episode&IncludeMedia=true&filters=IsNotFolder&fields=MediaStreams&Recursive=true&ImageTypeLimit=1&MinPremiereDate=2019-10-26&**searchTerm=Boy%2BMeets%E2%80%A6**&MaxPremiereDate=2019-10-26&Limit=16)

Its probably a Unicode character.

EDIT
Yeah it is a unicode character: %E2%80%A6

**Comment by faush01** [comment]
> 
> 
> > You might be able to use the NEW_SEARCH type:
> > ?mode=NEW_SEARCH&item_type=movie&query=All%2BMight
> 
> What's the difference between this one and the other?

All these modes are used internal for the addon, the main one that was exposed for use externally was the GET_CONTENT using the url, the url is passed directly to the Emby server, this was to allow 3rd party addons to use EmbyCon to query the server for items based on a server query url.

Other modes are used internally for different tnings and most of these build the server url dynamically, the search one is like this in that it takes a query string and builds an Emby server url from the data.

> I actually wanted to ask you something about a use case I don't know this new functionality could help with. The episodes in the Emby server are scraped using TVDB but TheMovieDB Helper uses TMDB. Normally I can use the episode title in a search but there are cases, specially with anime, where the name differs. I've seen that I can bypass the limitation by using the premiered date instead of the name of the episode but for that I need the ParentId from Emby for the TV show. Normally this wouldn't be a problem as for TV shows Emby has the TMDB id of the show but that would mean making two calls to Emby (first one to find the ParentId and second to make a search with premiered date and ParentId) which I can't do through TheMovieDB Helper. Is there any way I can pass the TV show TMDB ID plus the search string so EmbyCon takes care of transforming the TMDB ID into the ParentId?

As I said it might be best to add a new custom mode=EXTENDED_SEARCH that will take a bunch of search parameters and then dynamically build a search URL that it uses to query the Emby server.

**Comment by juanma-cvega** [comment]
> Yeah it is a unicode character: %E2%80%A6

Well, apparently I wasn't using the right version. I tried again with the latest one and now the character seems to be properly encoded, instead of **\xe2\x80\xa6** I get **%E2%80%A6** which is sent to Emby.

**Comment by juanma-cvega** [comment]
> As I said it might be best to add a new custom mode=EXTENDED_SEARCH that will take a bunch of search parameters and then dynamically build a search URL that it uses to query the Emby server.

Ok, I'll take a look at creating a new one that searches for the parentId from the TV show TMDB id.

**Comment by juanma-cvega** [comment]
I'm closing this pull request and creating another one for the label2 creation.

**Pull request closed without merging**
