### PR TITLE
add Use HTTPS, handle unsupported skin in set default views

### PR DESCRIPTION
**Pull request by anxdpanic**
Changes to skins, 
- don't use '-' as None
- reason: https://forum.kodi.tv/showthread.php?tid=298565&pid=2534486#pid2534486

### CODE REVIEW

**Comment by anxdpanic** [comment]
unable to directly test HTTPS myself

**Comment by faush01** [comment]
did you test the HTTPS option? I am having a few issues.

**Comment by anxdpanic** [comment]
No, I added a comment about that. Have no https set up currently to test that. You have any idea what may be missing? Didn't look like anything more should be required.

**Comment by faush01** [comment]
testing now, no big problem I think, it is just picking up the wrong port from somewhere I need to sort out.

**Comment by faush01** [comment]
ok so image url needed some work as well.
think I am getting closer.
this is going to require a lot of testing though.

**Comment by anxdpanic** [comment]
I should be able to get https set up tomorrow, and do some testing. If you need me to remove / separate use_https out of this pr let me know.

**Comment by faush01** [comment]
I am getting close, I think I just have the server detect code to sort out now.
I will commit all these changes to a new branch and post here when done, you can then test that branch.

**Comment by faush01** [comment]
created a branch
feature/use_https
all changes are there, if you could test with https that would be good.

**Comment by anxdpanic** [comment]
looks good so far on my test environment, alpha tagged it and pushed it to my main use set up to live test as well.

**Comment by faush01** [comment]
I just made a few changes to use {server} and {userid} in the URLs, this allows changes to the addon settings to be picked up in favorites and saved custom menu items as you are saving the place holder text and that is filled in when you do the actual data load for the url.

I was waiting for luke to get back to me on how I can auto detect the HTTPS settings (port) but he has not come back to me so I might just release this as is.

Can you test the latest {server} and {userid} changes and let me know how get get on. If all good I will do a release.

**Comment by faush01** [comment]
The port I am asking Luke about auto detect HTTPS
https://emby.media/community/index.php?/topic/48427-server-detect-https/

**Comment by anxdpanic** [comment]
So far so good, moved it to my main environment again too so I can test regular usage. Tried favorites and switching between https/http with no issues. 

Not sure on the server detect, no multicast over the vpn to my server. Did notice that if no server is returned, server detect opens an empty cancel only dialog.

**Comment by faush01** [comment]
I made it show the empty dialog to show that it could not find any servers, I guess a better result would be an ok dialog with a message stating no servers found.

**Comment by anxdpanic** [comment]
I just did that, and adding confluence to the json. can pr those against use_https

**Comment by anxdpanic** [comment]
actually, I did just a regular notification. Would you prefer I change that to an ok dialog?

All the testing of views in confluence and still no issues

**Comment by faush01** [comment]
this pull request is now redundant, closing

**Pull request closed without merging**
