### PR TITLE
Playback updates

### PR DESCRIPTION
**Pull request by anxdpanic**
- immediate playback
- 'Play from here' working

### CODE REVIEW

**Comment by faush01** [comment]
So in what situation would the handle be -1

**Comment by faush01** [comment]
Thx I will have a play with this when I get time.

**Comment by anxdpanic** [comment]
I've rebased and removed my unnecessary use of global, and the re-declarations that were unneeded.
If there's anything else this needs let me know.

**Comment by faush01** [comment]
This is absolutely on my todo list to look at, I had a few small bugs to sort out last weekend, hopefully in the next few days I can get to this.

**Comment by faush01** [comment]
Why not just use xbmc.Player().play() all the time? I assume it  works regardless the handle being -1 or not.

**Comment by anxdpanic** [comment]
Player().play() does actually work from widget and in add-on. Went off setResolvedUrl being the standard for add-ons, given the shortcomings with startoffset though Player().play() would be better for both. Want that commented out or removed?

**Comment by faush01** [comment]
I played with this a while ago when I first tried to get it all working consistently and the only way I could get it to work consistently and reliably was to use the service approach.
I will have a play with your code and see how it works in the different scenarios.
I remember these being some of my problems when I was playing with this last time:
 - plugin playback failing (Taking to long), I can not remember the details
 - resuming not working in some situations
 - Kodi watched status always overriding what the plugin sets (This is fixed in Kodi 18)

Things to test:
 - Playback works from all location in Kodi, listings, home page, widgets, favorites etc
 - Resume position correctly being used from ListItem for display of items i.e. Emby has 25% played and Kodi shows it correctly, this can show up when Kodi marks items internall as played when playback finishes

**Comment by anxdpanic** [comment]
Updated to player.play only, will test specifically for those as I find the time.

**Comment by faush01** [comment]
Playing from the Info screen fails.
Hit 'i' to bring up the information screen for an item, select play. It will not play.

I remember now this was one of the issues I was having.

**Comment by anxdpanic** [comment]
Yea, also issues with double dialog from widgets. Going to close for now, likely better to revisit for a future Kodi version.

**Comment by faush01** [comment]
I remember months ago spending days looking at this. The only way I could get consisted playback from all areas of Kodi was to use the service poll approach. I know it looks like a hack and it mostly is but it does give consistent playback experience even if it is a little limited from all areas of Kodi.

Yes there are a few changes (that I made via PR) to Kodi 18 that allow you to have the result of the official resume dialog passed to addons when they are called.

I was going to wait until Kodi 17 is out and then revisit the playback situation.

**Comment by faush01** [comment]
By the way, thanks for looking at this, I was unble to get anyone from the Kodi team or the Emby forums interested in this at the time and it is good to have someone else also hacking away trying to solve these issues.

**Comment by anxdpanic** [comment]
The consistency is definitely worth more than anything the changes brought. Was thinking the same thing as far as timing. Happy to any time I can 👍

**Pull request closed without merging**
