### PR TITLE
don't show login dialog during startup

### PR DESCRIPTION
**Pull request by sualfred**

### CODE REVIEW

**Comment by faush01** [comment]
There are a lot of changes in that pr, did you really change everything?

Potentially this check only needs to happen once when the service starts.

**Comment by sualfred** [comment]
It's only the commit that looks that strange. It's just the check + if clause indentation of the lines of the rest.

**Comment by faush01** [comment]
why not just this at the start of the service
```

for i in range(100):
    if not xbmc.getCondVisibility("Window.IsVisible(startup)"):
        break
    xbmc.sleep(100)
```

**Comment by sualfred** [comment]
changes manually applied with adjustments. PR closed

**Pull request closed without merging**
