### PR TITLE
add debug logging to strm processing, and gracefully fail

### PR DESCRIPTION
**Pull request by anxdpanic**
…ack url is found

### CODE REVIEW

**Comment by anxdpanic** [comment]
Wheemer provided the strm causing him issues, I will be able to check on it this afternoon and will update this pr accordingly.

**Comment by faush01** [comment]
No problem, do you know if there is a strm  file spec somewhere

**Comment by anxdpanic** [comment]
There is no specifics that I've been able to find. Though url is always a single a line, and #KODIPROP was introduced for inputstream addons to set required properties.

This is the contents of a valid dash strm:
#KODIPROP:inputstreamaddon=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
http://download.tsi.telecom-paristech.fr/gpac/DASH_CONFORMANCE/TelecomParisTech/mp4-live/mp4-live-mpd-AV-BS.mpd

The issue with Wheemer's is that newline isn't being recognized, even with regex using ^.+?$

**Comment by anxdpanic** [comment]
Okay so this seems like something we can't fix in add-on, it appears the \n is being removed when returned by Emby.

contents =  #EXTINF:-1,Marvel's The Punisher - S01E01plugin://plugin.video.netflix/?action=play_video&video_id=80117697

no line break included.

**Comment by faush01** [comment]
hehe I just came up with the same conclusion.

**Comment by anxdpanic** [comment]
hah, just replied at the same time on the forum too. My multiline strms are testing fine with CRLF, it looks like Wheemer's uses \n (LF) only and it's being dropped.

**Comment by anxdpanic** [comment]
This PR should be good unless you have any requests, should make future debugging of strms much clearer.

**Comment by faush01** [comment]
There are a lot of changes here, my diffs exploded.
If this is just logging why so many changes

**Comment by anxdpanic** [comment]
It's an indentation https://github.com/faush01/plugin.video.embycon/pull/17/files#diff-3def453c8ac78a33a776eb3bc5dedff2L95
to handle None being returned by stream in a malformed strm file.

**Comment by anxdpanic** [comment]
Sorry forgot second reference. 
https://github.com/faush01/plugin.video.embycon/pull/17/files#diff-3def453c8ac78a33a776eb3bc5dedff2R100

**Comment by faush01** [comment]
but you dont need the playurl check as it is always going to contain a play

**Comment by anxdpanic** [comment]
in a malformed strm like Wheemer's playurl is None

**Comment by anxdpanic** [comment]
I could change that to an if not raise, or if not notify instead of just failing gracefully.

**Comment by faush01** [comment]
yeah but that is fine as then it will try to build a url using the normal method, is it possible to have both?

**Comment by faush01** [comment]
Would it not be better to after this line

playurl, listitem_props = PlayUtils().getStrmDetails(result)

just do

if playurl is None:
   return

**Comment by anxdpanic** [comment]
Strm can't be handled by direct stream or transcode. I've updated the pr to return if strm is None.

**Pull request merged**
