### PR TITLE
Artwork enhancements

### PR DESCRIPTION
**Pull request by puenktchen**

### CODE REVIEW

**Comment by faush01** [comment]
Add a description with some context about why you want the changes, what will they allow you to do?

It all looks very hard coded, think about a way of doing this dynamically.

It looks like you have removed some art, why, how have you tested this works.

It looks like you have renamed some variables for no functional reason, this makes it harder to see the actual functional changes.

**Comment by faush01** [comment]
Are the extra fanart images usable in Kodi?

**Comment by puenktchen** [comment]
> Add a description with some context about why you want the changes, what will they allow you to do?
> 
> It all looks very hard coded, think about a way of doing this dynamically.
> 
> It looks like you have removed some art, why, how have you tested this works.
> 
> It looks like you have renamed some variables for no functional reason, this makes it harder to see the actual functional changes.

I will provide a new commit that dynamically provides the fanart properties
and also has the missing description/reasons. Sorry for that!

>Are the extra fanart images usable in Kodi?

It depends on the skin implementation. I've also asked the artworkhelper developer for support:
https://github.com/rmrector/script.artwork.helper/issues/2

**Comment by faush01** [comment]
I dont think you need all the changes to the getArtwork function, you can just add the index for the background you want and call it with increasing indexes.

**Comment by puenktchen** [comment]
Already done. Just wait for my next commit 😉

**Comment by sualfred** [comment]
@puenktchen 
The removal of the other artwork info labels is not a good idea. Some skins will not show them in that case. A lot skins differs between plugin and library paths. That was the reason why I've added "tvshow.fanart" and "fanart" for seasons/episodes for example.  With this approach we are 100% sure that the artworks are available in all skins and their implementation.

And a fallback if ListItem.Poster is empty is wrong for episodes. Episodes have no poster. Some skins, and myself too, are choosing the aspect ratio based on the info label. A poster is always ~2:3 but a episode thumb is 4:3-16:9. Some of them also choose the layout based on the existence of values. Episodes have no ListItem.Poster at all :)

**Comment by faush01** [comment]
closing this for now, can be revisited but would need to be rebased and looked at again

**Pull request closed without merging**
