### PR TITLE
artwork, Window props, minor fix play reporting, unused imports

### PR DESCRIPTION
**Pull request by anxdpanic**
Artwork refactor
- get all listitem artwork from single function
- tested in Confluence, Estuary, and Estuary Mod
- confirmed widgets in Estuary and Mod

Fix service reporting last item being played when play started from elsewhere if embycon item had been played

prefix all Home window properties with addon-id
- no other add-ons should conflict
- will be required for official repo

Minor clean up

### CODE REVIEW

**Comment by anxdpanic** [comment]
Only done a quick retest, haven't noticed anything unexpected so far. Will follow up in a bit after some additional tests

**Comment by anxdpanic** [comment]
Should be good to go

Home.xml will need to be re-copied with the change to property prefixing

**Comment by faush01** [comment]
there are still a few instances of xbmcgui.Window(10000) around, any reason you did not change them to use the new HomeWindow() class?

**Comment by anxdpanic** [comment]
Got them now, they are squashed in to the home window commit

**Comment by anxdpanic** [comment]
looks like that introduced an issue, will resolve asap

**Comment by anxdpanic** [comment]
Resolved, that introduced a circular import, moved HomeWindow to a utils2.py

**Comment by faush01** [comment]
not sure I like utils2.py how about kodi_utils.py and we can put all the kodi specific utils classes and functions in there

**Comment by anxdpanic** [comment]
Can do, is there anything else you think might fit at the moment to be moved? getKodiVersion ?

**Comment by faush01** [comment]
yeah it sounds like a good place to put all the kodi functions that are just kodi related, anything that just interacts with Kodi and is a helper function should go there.

**Comment by anxdpanic** [comment]
renamed, and moved getKodiVersion and addDirectoryMenuItem to kodi_utils as well

**Comment by faush01** [comment]
looks good, I will do some testing today and if all goes well I will merge it

**Comment by anxdpanic** [comment]
Not sure how else to reach you, left a note here: https://github.com/anxdpanic/script.embycon.widgets/issues/1

**Pull request merged**
