### PR TITLE
Add missing required Md5 for authentication

### PR DESCRIPTION
**Pull request by baikunz**
Woops still missing md5 password format for the authentication system to work fully :/
Could not get it to work without the 3 specified formats.

### CODE REVIEW

**Comment by faush01** [comment]
Is this actually not working for you or are you just trying to fully follow the docs.

Md5 is not needed.

**Comment by baikunz** [comment]
It's not working ! On my setup at least. At first I thought it would work without it and just using plain text. But I kept getting 401's.
So it looks like the 3 of them are actually needed. At least for my setup.

**Comment by faush01** [comment]
What version of the server are you using? Is it latest stable?

**Comment by baikunz** [comment]
Actually I have no idea :( I'm not hosting my own emby. I can ask, but I think it's pretty up to date.

**Comment by faush01** [comment]
Then this is not your issue.

**Comment by baikunz** [comment]
Well I don't get the logic here :s Since EmbyCon is an Emby client I don't get why it's not supposed to be my issue. 
The thing is, I could not connect to the server if any of the 3 password format was missing, I tried with sha1 only, then sha1 and md5, then sha1 and plain text, it only worked when I provided the 3 passwords.
If it's the fact that it's not my own emby server that bothers you, I could easily setup my own and try to reproduce the issue. But this is clearly a client side issue, and if I encountered it, some users may face it too.

I just wanted to help, I could just have used my fixed branch, but why not share it ?

**Comment by faush01** [comment]
This code has not changed in years, it is working for me on both the stable version and the beta version of the server and no one else has any issues with this and there are hundreds of users of the addon I dont see how it can a client issue.
I can not reproduce this, if you can set up a server and let me know how to reproduce it that would be great.

**Comment by faush01** [comment]
I had a chat with the devs of the server.

One reason you might be seeing what you are seeing is that you are using your Emby Connect password to when logging into EmbyCon.

Are you using the same password you use to log into the forums with?

Confirm with the server owner if you are using the correct password, this should be the server username and password NOT your Emby Connect (forum) password.

**Comment by faush01** [comment]
Also can you confirm the version of the server please, this will help track down what is happening.

**Comment by baikunz** [comment]
Yep this is exactly it ! I'm connecting to the server as an Emby Connect user ;-) Had no time today to look around the issue, I'll try to look at it ASAP!
Thanks for your help ;-)

**Comment by faush01** [comment]
In newer versions of the server the server will use the clear text password to do the auth for all of the available auth types which includes Emby Connect. That is why I was asking about the server version to confirm it was pre that version that was doing this (about 3 months old).
I was unaware the server used the md5 password for auth against Emby Connect, this was something that is not documented. It was only when the server devs mentioned it that I realised what was going on.
In a few months the server is going to ignore the all hashed passwords and just use the clear text one. At that point I will have to make a decisions about what to do with the default connection type, I think I will default to SSL/HTTPS then.

**Comment by baikunz** [comment]
Hello,
Sorry I completely forgot to look into this issue. Well it seems that we can close this PR. MD5 and SH1 won't be needed in a few weeks anyway !
I'll just keep using my branch in the meantime since it looks no one except me is using Emby Connect :D 
Yep default to SSL seems a good idea. I'd rather not have my password sent in clear !

**Pull request closed without merging**
