### PR TITLE
Batch of updates

### PR DESCRIPTION
**Pull request by anxdpanic**
- allow unlisted users
- support strm playback
- update server_detect
optional notify
add change_user parameter
add user input and user defined to username selection
test settings host:port connection when force and no servers returned
- i18n
- other minors

### CODE REVIEW

**Comment by anxdpanic** [comment]
all tested locally, may want to test detect server and change user in your configuration as well

**Comment by faush01** [comment]
Looks good. Merging.

**Comment by faush01** [comment]
I will do some testing on this today and try to get a release out.

**Comment by anxdpanic** [comment]
Thanks 👍  Do you have any sort of TODO? Be happy to try to help out as time allows.

**Comment by faush01** [comment]
no TODO list.
this addon is not going to be a feature rich as the main addon but it will allow people to play back their tv shows and movies.
the end game is to have this addon in the official Kodi Repo.
the last item I want to look at is the double resume dialogs that show but for now the work around is going to have to be good enough until I can dig into Kodi source and see if it is possible or not.

**Comment by anxdpanic** [comment]
iirc you used to be able to do listitem.setInfo('video', {'overlay': 6, 'playcount': 0}), but I tested that and it no longer seems to have any effect.

**Comment by faush01** [comment]
the resume is being picked up by playback percentage being set in the ListItem, this is fine as it is needed by the skin to show the progress bar at the bottom of the items, the problem is Kodi then askes if you want to resume but there is no way to interacting of getting the answer of this dialog into the addon so then the addon needs to ask again.

the whole root cause of this is me using a very different approach to playback than what is intended due to some areas of the Kodi system starting playback differently than others. I use a background thread to monitor a windows prop and if it is here play the URL it contains, this removes the need for the addon play action to have to try to start the playback itself which was causing me a great deal of issues when trying to play back an intem from different locations like from a normal list or from a home page widget or from a remote action or from the Media Info screen. I was getting very inconsistent results when I was trying to start playback from all these different areas of Kodi, this way it mostly works apart from the double resume prompt.

I guess I could just stop adding the play percentage but that would stop the progress bar skin item from showing for partially played items. Since there is a work around I am happy with the result at the moment.

**Pull request merged**
